"""design_system —— system_monitor 深色 UI 设计系统的可复用 PySide6 实现。

把原项目的深色主题、指标卡片、实时曲线、工具栏与标签样式提炼为独立包，
未来任意 Qt 项目只需：

    from PySide6.QtWidgets import QApplication, QMainWindow
    from design_system import apply_dark_theme, MetricCard, create_time_series_chart, style_toolbar

    app = QApplication(sys.argv)
    apply_dark_theme(app)

即可套用同一套视觉设计。设计令牌全部集中在 tokens 模块，便于统一调整。
"""

from .tokens import (
    BG_WINDOW, BG_APP, BG_PANEL, BG_CARD, BG_CARD_HOVER, BG_ELEVATED, BG_ACCENT,
    BORDER, BORDER_CARD, BORDER_INPUT, BORDER_HOVER, BORDER_BTN_HOVER,
    TEXT_PRIMARY, TEXT_SECONDARY, TEXT_MUTED, TEXT_MUTED2, TEXT_VALUE, TEXT_BRIGHT,
    ACCENT, ACCENT_BTN, ACCENT_BTN_HOVER,
    METRIC_CPU, METRIC_MEM, METRIC_NET_UP, METRIC_NET_DOWN,
    METRIC_DISK_READ, METRIC_DISK_WRITE, METRIC_GPU,
    THRESHOLD_WARN, THRESHOLD_CRIT, COLOR_WARN, COLOR_CRIT,
    CORE_PALETTE,
    FONT_TITLE_SIZE, FONT_TITLE_WEIGHT, FONT_TITLE_COLOR, FONT_TITLE_SPACING,
    FONT_VALUE_SIZE, FONT_VALUE_WEIGHT, FONT_VALUE_COLOR, FONT_VALUE_SPACING,
    FONT_SECONDARY_SIZE, FONT_MUTED_SIZE, FONT_SECONDARY_COLOR,
    SPACING_CARD, SPACING_INNER, SPACING_GRID, SPACING_TOOLBAR, TOOLBAR_PADDING,
    CARD_PADDING, TAB_PADDING, CHART_MARGIN, CHART_MARGIN_MINI,
    RADIUS_CARD, RADIUS_BAR, RADIUS_BAR_CHUNK, RADIUS_TAB, RADIUS_INPUT, RADIUS_BTN,
    DASHBOARD_COLS, CORE_GRID_MAX_COLS, UPDATE_INTERVAL_MS, PROGRESS_BAR_HEIGHT,
)
from .theme import apply_theme, apply_dark_theme, style_toolbar, THEME_QSS, THEME_QSS_LIGHT
from .widgets import MetricCard, TimeSeriesChart
from .charts import create_time_series_chart

__all__ = [
    "apply_theme", "apply_dark_theme", "style_toolbar", "THEME_QSS", "THEME_QSS_LIGHT",
    "MetricCard", "TimeSeriesChart", "create_time_series_chart",
    # 令牌
    "BG_WINDOW", "BG_APP", "BG_PANEL", "BG_CARD", "BG_CARD_HOVER", "BG_ELEVATED", "BG_ACCENT",
    "BORDER", "BORDER_CARD", "BORDER_INPUT", "BORDER_HOVER", "BORDER_BTN_HOVER",
    "TEXT_PRIMARY", "TEXT_SECONDARY", "TEXT_MUTED", "TEXT_MUTED2", "TEXT_VALUE", "TEXT_BRIGHT",
    "ACCENT", "ACCENT_BTN", "ACCENT_BTN_HOVER",
    "METRIC_CPU", "METRIC_MEM", "METRIC_NET_UP", "METRIC_NET_DOWN",
    "METRIC_DISK_READ", "METRIC_DISK_WRITE", "METRIC_GPU",
    "THRESHOLD_WARN", "THRESHOLD_CRIT", "COLOR_WARN", "COLOR_CRIT",
    "CORE_PALETTE",
    "FONT_TITLE_SIZE", "FONT_TITLE_WEIGHT", "FONT_TITLE_COLOR", "FONT_TITLE_SPACING",
    "FONT_VALUE_SIZE", "FONT_VALUE_WEIGHT", "FONT_VALUE_COLOR", "FONT_VALUE_SPACING",
    "FONT_SECONDARY_SIZE", "FONT_MUTED_SIZE", "FONT_SECONDARY_COLOR",
    "SPACING_CARD", "SPACING_INNER", "SPACING_GRID", "SPACING_TOOLBAR", "TOOLBAR_PADDING",
    "CARD_PADDING", "TAB_PADDING", "CHART_MARGIN", "CHART_MARGIN_MINI",
    "RADIUS_CARD", "RADIUS_BAR", "RADIUS_BAR_CHUNK", "RADIUS_TAB", "RADIUS_INPUT", "RADIUS_BTN",
    "DASHBOARD_COLS", "CORE_GRID_MAX_COLS", "UPDATE_INTERVAL_MS", "PROGRESS_BAR_HEIGHT",
]
